@startuml
  top to bottom direction
  hide empty description
  skinparam nodesep 65
  
  [*] --> Создан : Покупатель оформил заказ
  Создан --> Ожидание_оплаты : Покупатель перешел к оплате
  Ожидание_оплаты --> Оплачен : Успешная оплата
  Ожидание_оплаты --> Отменен : Ошибка оплаты / Покупатель отменил заказ
  Оплачен --> Подготовка_к_отправке : Заказ принят в обработку
  Подготовка_к_отправке --> Отправлен : Товар передан в службу доставки
  Отправлен --> Доставлен : Товар доставлен покупателю
  Доставлен --> Возврат : Покупатель инициировал возврат
  Доставлен --> Завершен : Покупатель подтвердил получение
  Возврат --> Завершен : Возврат обработан
  Подготовка_к_отправке --> Отменен : Заказ отменен менеджером
  Отменен --> [*]
  Завершен --> [*]
@enduml
